version: "3.7"

networks:
  lifecms_network:
    driver: bridge

services:
  sql.data:
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    networks:
      - lifecms_network
    restart: always
    volumes:
      - ./docker/provision/mysql/init:/docker-entrypoint-initdb.d

  identity.api:
    image: lifecms_identity.api:latest
    entrypoint: /bin/sh -c "waitforit.sh sql.data:3306 -- dotnet /app/Identity.API.dll"
    ports:
      - "5002:80"
    build:
      context: ./
      dockerfile: ./src/Services/Identity/Identity.API/Dockerfile
    environment:
      SQL_DB_HOST: sql.data
      ConnectionStrings__LifeCMSIdentity: Server=sql.data;Database=lifecms_identity;Uid=lifecms_user;Password=lifecms_pass;AllowUserVariables=True;
      ConnectionStrings__LifeCMSIdentityServer: Server=sql.data;Database=lifecms_identity_server;Uid=lifecms_user;Password=lifecms_pass;AllowUserVariables=True;
      IdentityServerAuthentication__Authority: "http://localhost:5002"
      ApiResources_0_Name: WebApi
      ApiResources_0_Scopes_0_Name: post:read
      ApiResources_0_Scopes_0_DisplayName: "Read access to the Post resource"
      Clients__WebApiClient__AllowedCorsOrigins__0: http://localhost:5000
      Clients__WebApiClient__AllowedScopes__0: post:read
      Clients__WebApiClient__ClientId: WebApiClient
      Clients__WebApiClient__ClientName: WebApiClient
      Clients__WebApiClient__PostLogoutRedirectUris__0: http://localhost:5000/signout-callback-oidc
      Clients__WebApiClient__RedirectUris__0: http://localhost:5000/session/oauth_callback
      Clients__WebApiClient__RequireConsent: "false"
      Clients__WebApiClient__RequireClientSecret: "false"
    depends_on:
      - sql.data
    networks:
      - lifecms_network
    volumes:
      - type: bind
        source: ./docker/waitforit.sh
        target: /usr/local/bin/waitforit.sh

  contentcreation.api:
    image: lifecms_contentcreation.api:latest
    entrypoint: /bin/sh -c "waitforit.sh sql.data:3306 -- dotnet /app/ContentCreation.API.dll"
    ports:
      - "5001:80"
    build:
      context: ./
      dockerfile: ./src/Services/ContentCreation/ContentCreation.API/Dockerfile
    environment:
      SQL_DB_HOST: sql.data
      ConnectionStrings__LifeCMS: Server=sql.data;Database=lifecms_production;Uid=lifecms_user;Password=lifecms_pass;AllowUserVariables=True;
    depends_on:
      - sql.data
    networks:
      - lifecms_network
    volumes:
      - type: bind
        source: ./docker/waitforit.sh
        target: /usr/local/bin/waitforit.sh

  web.webspa:
    image: web.webspa:latest
    ports:
      - "5000:80"
    build:
      context: ./
      dockerfile: ./src/Web/WebSPA/Dockerfile
    volumes:
      - ./docker:/usr/local/bin/docker
    environment:
      REACT_APP_RUNTIME_API_HOST: http://localhost:5001/api
      REACT_APP_RUNTIME_AUTHORITY: http://localhost:5002
      REACT_APP_RUNTIME_CLIENT_ID: WebApiClient
      REACT_APP_RUNTIME_POST_LOGOUT_REDIRECT_URI: http://localhost:5000
      REACT_APP_RUNTIME_REDIRECT_URI: http://localhost:5000/session/oauth_callback
      REACT_APP_RUNTIME_RESPONSE_TYPE: code
      REACT_APP_RUNTIME_SCOPE: post:read
      REACT_APP_RUNTIME_WEBSOCKET_HOST: http://localhost:5001/services/websocket