version: '3'

services:
  sql.data:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: socialite_dbuser
      MYSQL_PASSWORD: socialite_pass
      MYSQL_DATABASE: socialite_production

  socialite.webapi:
    image: socialite_webapi:latest
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SQL_DB_HOST: sql.data
      ConnectionStrings__Socialite: Server=sql.data;Database=socialite_production;Uid=socialite_dbuser;Password=socialite_pass;AllowUserVariables=True;
    depends_on:
      - sql.data

  react-client:
    image: socialite_react-client:latest
    ports:
      - "80:80"
      - "3000:3000"
    build:
      context: ./Socialite.ReactClient
      dockerfile: Dockerfile