version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.8-aspnetcore-runtime
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build Socialite.UnitTests
