version: 2
jobs:
  build:
    docker:
      - image: lifecms/dotnet-sdk-yarn:5.0
      - image: mysql/mysql-server:8.0
        environment:
          MYSQL_ROOT_HOST: "%"
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_USER: lifecms_dbuser
          MYSQL_PASSWORD: lifecms_pass
          MYSQL_DATABASE: lifecms_test
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Installing dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1

      - run:
          name: Waiting for MySQL to be ready
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s

      - run: find .

      - run:
          name: Building LifeCMS
          command: dotnet build

      - run:
          name: Executing unit tests
          command: dotnet test /p:CollectCoverage=true  /p:Include=\"[LifeCMS.Services.ContentCreation.Domain]*,[LifeCMS.WebAPI]*\" /p:CoverletOutputFormat=json /p:CoverletOutput=./../coverage/unit.tests.json ./src/Services/ContentCreation/ContentCreation.UnitTests

      - run:
          name: Executing integration tests
          command: dotnet test /p:CollectCoverage=true  /p:Include=\"[LifeCMS.Services.ContentCreation.Domain]*,[LifeCMS.WebAPI]*\" /p:CoverletOutputFormat=opencover /p:CoverletOutput=./../coverage/LifeCMS_coverage.xml /p:MergeWith="./../coverage/unit.tests.json" ./src/Services/ContentCreation/ContentCreation.IntegrationTests
          environment:
            ConnectionStrings__LifeCMSIntegrationTests: Server=localhost;Database=lifecms_test;Uid=root;AllowUserVariables=True;
