version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build /p:CollectCoverage=true  /p:Include="[Socialite.*]*" /p:Exclude="[*]Socialite.Infrastructure.Migrations.*" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./lcov.info Socialite.UnitTests
      - run: bash <(curl -s https://codecov.io/bash)
