const MarketingStarter = {
    ROOT: {
        type: 'div',
        isCanvas: true,
        props: {
            className: 'css-nwc33h',
        },
        displayName: 'Element',
        custom: {},
        hidden: false,
        nodes: [
            'c75v0YfFY',
            'nCR2cuxAq',
            '8iadpE7SK',
            'Advfxz5fq',
            'GP69UymHu',
            'Nbq36gFSc',
        ],
        linkedNodes: {},
    },
    c75v0YfFY: {
        type: {
            resolvedName: 'Image',
        },
        isCanvas: false,
        props: {
            backgroundColor: '#fff',
            padding: [
                0.1,
                0.2,
                0.1,
                0.2,
            ],
            newFile: {
                name: '',
                size: 0,
                contentType: '',
                url: null,
            },
        },
        displayName: 'Image',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
    },
    nCR2cuxAq: {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: false,
            italic: false,
            underline: false,
            fontSize: 2,
            padding: [
                1,
                1,
                0,
                1,
            ],
            text: 'The Marketing Starter',
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
    },
    '8iadpE7SK': {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: true,
            italic: false,
            underline: false,
            fontSize: 1,
            padding: [
                1,
                1,
                1,
                1,
            ],
            text: 'A starter template for a winning campaign.',
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
    },
    Advfxz5fq: {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: false,
            italic: false,
            underline: false,
            fontSize: 1,
            padding: [
                1,
                1,
                1,
                1,
            ],
            text: "Now you've got a template selected, you can add new content components by dragging and dropping them onto the editor from the \"Create\" menu on the right-hand side of this editor, or customise the components that have already been placed.",
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
    },
    GP69UymHu: {
        type: {
            resolvedName: 'Columns',
        },
        isCanvas: false,
        props: {
            backgroundColor: '#fff',
            padding: [
                1,
                0,
                1,
                0,
            ],
            columnCount: 2,
        },
        displayName: 'Columns',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {
            'row-item-0': 'pMrN5XKOU',
            'row-item-1': 'IoLrOiI-zD',
        },
        parent: 'ROOT',
    },
    pMrN5XKOU: {
        type: 'div',
        isCanvas: true,
        props: {
            className: 'css-45efv3',
            hidden: false,
        },
        displayName: 'Element',
        custom: {},
        hidden: false,
        nodes: [
            'dW55bnmEA',
            'Y2_JshQQJ',
        ],
        linkedNodes: {},
        parent: 'GP69UymHu',
    },
    'IoLrOiI-zD': {
        type: 'div',
        isCanvas: true,
        props: {
            className: 'css-45efv3',
            hidden: false,
        },
        displayName: 'Element',
        custom: {},
        hidden: false,
        nodes: [
            '2IkXIa7XK',
        ],
        linkedNodes: {},
        parent: 'GP69UymHu',
    },
    dW55bnmEA: {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: true,
            italic: false,
            underline: false,
            fontSize: 1,
            padding: [
                1,
                1,
                0,
                1,
            ],
            text: 'Quick Tip',
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'pMrN5XKOU',
    },
    '2IkXIa7XK': {
        type: {
            resolvedName: 'Image',
        },
        isCanvas: false,
        props: {
            backgroundColor: '#fff',
            padding: [
                0.1,
                0.2,
                0.1,
                0.2,
            ],
            newFile: {
                name: '',
                size: 0,
                contentType: '',
                url: null,
            },
        },
        displayName: 'Image',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'IoLrOiI-zD',
    },
    Y2_JshQQJ: {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: false,
            italic: false,
            underline: false,
            fontSize: 1,
            padding: [
                1,
                1,
                1,
                1,
            ],
            text: 'Use rows and columns to create a dynamic layout, present a story against a feature image.',
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'pMrN5XKOU',
    },
    Nbq36gFSc: {
        type: {
            resolvedName: 'Text',
        },
        isCanvas: false,
        props: {
            bold: false,
            italic: true,
            underline: false,
            fontSize: 1,
            padding: [
                1,
                1,
                1,
                1,
            ],
            text: 'Did you know? You can click a component, and delete it from the layout by clicking the "rubbish bin icon" within the "Style" tab on the right-hand side of the editor. ',
        },
        displayName: 'Text',
        custom: {},
        hidden: false,
        nodes: [],
        linkedNodes: {},
        parent: 'ROOT',
    },
};

export default MarketingStarter;
